/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "tertiary-fixed": "#d7e3ff",
                "surface-container-highest": "#dde4e6",
                "surface-gray": "#F5F5F7",
                "on-primary-container": "#fff7f5",
                "on-secondary-container": "#364d83",
                "surface-container-lowest": "#ffffff",
                "surface-container": "#e8eff1",
                "surface-container-low": "#eef5f7",
                "surface-container-high": "#e2e9ec",
                "secondary": "#001F54",
                "on-background": "#161d1f",
                "on-error-container": "#93000a",
                "on-secondary-fixed-variant": "#2e457b",
                "surface-tint": "#c00000",
                "on-secondary": "#ffffff",
                "tertiary": "#0058b1",
                "pulse-red-light": "#FFEBEE",
                "inverse-on-surface": "#ebf2f4",
                "on-surface-variant": "#5f3f3a",
                "outline-variant": "#e9bcb5",
                "on-tertiary": "#ffffff",
                "primary-fixed-dim": "#ffb4a8",
                "outline": "#946e68",
                "background": "#f4fafd",
                "on-primary-fixed-variant": "#930100",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#aac7ff",
                "on-primary": "#ffffff",
                "on-error": "#ffffff",
                "surface-bright": "#f4fafd",
                "inverse-primary": "#ffb4a8",
                "background-white": "#FFFFFF",
                "surface-variant": "#dde4e6",
                "surface-dim": "#d4dbdd",
                "primary-container": "#e60000",
                "primary-fixed": "#ffdad4",
                "secondary-fixed": "#dae2ff",
                "tertiary-container": "#1d70d7",
                "on-surface": "#161d1f",
                "on-tertiary-container": "#f7f8ff",
                "on-tertiary-fixed-variant": "#00458e",
                "secondary-container": "#a9c0fe",
                "on-secondary-fixed": "#001946",
                "primary": "#E60000",
                "secondary-fixed-dim": "#b1c5ff",
                "on-tertiary-fixed": "#001b3e",
                "error": "#ba1a1a",
                "on-primary-fixed": "#410000",
                "inverse-surface": "#2b3234",
                "medical-teal": "#1A939E",
                "charcoal": "#2D3436",
                "alert-red": "#E71D36",
                "signal-green": "#2ECC71",
                "brand-red": "#E60000",
                "brand-navy": "#001F54"
            },
            fontFamily: {
                sans: ["Inter", "sans-serif"],
                "mono-data": ["monospace"],
                "body-lg": ["Inter"],
                "headline-lg-mobile": ["Nunito Sans"],
                "label-md": ["Inter"],
                "headline-md": ["Nunito Sans"],
                "body-sm": ["Inter"],
                "body-md": ["Inter"],
                "headline-xl": ["Nunito Sans"],
                "headline-lg": ["Nunito Sans"]
            },
            spacing: {
                "margin-desktop": "48px",
                "margin-mobile": "16px",
                "container-max": "1280px",
                "gutter": "24px"
            },
            fontSize: {
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                "label-md": ["14px", {"lineHeight": "16px", "fontWeight": "600"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}